### ISSUE TITLE
Downopto broken...?

### ISSUE THREAD

**Issue by mrobe** [jaytohe/downopto#1]
This script looks really great, but I can't get it to work!

When I load the script using Tampermonkey, the syntax checker says this line has an error :

`   return axios.get(url, {`

Error is "axios is not defined".

How can I fix this? It must be something simple, but I'm not sure what.

Help!

**Comment by jaytohe** [comment]
Hi @mrobe!

That's odd. The axios js library is imported with the script so it should not error out. Can you try Violentmonkey?

Btw, I am not sure whether the script will still work as I haven't updated it for a while.

But you are welcome to give it a shot!

Best,

Jaytohe

**Comment by mrobe** [comment]
Thanks for your message!

I didn't know about Violentmonkey. I tried that and got further.

To ensure the script waits until the page loads, I added this to the script header:

`// @run-at      document-idle`

When I click on **Download All**, I see "called lecturesList" in the console, but the script stops there.

Maybe Panopto changed the DOM of the web pages?

**Comment by jaytohe** [comment]
Ok so I did some digging and as far as I can see the script fails to find the the video stream url when ran on Viewer.aspx pages. So they have definitely changed the DOM, yes. 

In List.aspx pages, which is what you were trying to run it on to bulk-download videos, it does get the video urls but gets 403 Forbidden when trying to download them (after clicking the Download All button).

 So it seems like Panopto has disabled direct access to mp4 video links (which is what the script relied on 2 years ago when I wrote it) :(

A way to fix it would be to get the url of the media **stream** and download the video chunk by chunk, typically an __m3u8__ file pointing to multiple __ts__ video and audio files.

I am pretty busy at the moment though so I'll have a crack at it when I am free.

**Comment by mrobe** [comment]
Sounds good. Thanks!

**Comment by jaytohe** [comment]
Good news! I managed to find a workaround to make it work again. I've tested it with my uni's panopto platform and it works. I'll add it as a pull request so you can test it as well :)

**Comment by jaytohe** [comment]
Checkout #2 and let me know if it works for you.

**Comment by mrobe** [comment]
Works better — thanks!!

**Comment by jaytohe** [comment]
> Works better — thanks!!

By _better_ you mean it actually works, right? Cus it was totally broken before 😅
