### ISSUE TITLE
Add support for panopto.com

### ISSUE THREAD

**Issue by CyberLykan** [jaytohe/downopto#3]
I just replace .eu with .com, but maybe you could make the script support both.

**Comment by jaytohe** [comment]
Hey @CyberLykan! Thanks for brining this up. I did not know panopto hosted content on .com domains as well. I have created a pull request #4 that adds supports for .com urls. Can you test it out? My laptop decided to die on me recently so I cannot test this right now :/

**Comment by CyberLykan** [comment]
Hi @jaytohe, sorry for not noticing your reply sooner.

The pull request seems to work fine.
